# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        Dialog.setMinimumSize(QtCore.QSize(508, 259))
        Dialog.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/ResourceImage/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 560, 430))
        self.label.setStyleSheet("border-image: url(:/Background/ResourceImage/Abstract 2.png);\n"
"border-bottom-right-radius: 50px;\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.runButton = QtWidgets.QPushButton(Dialog)
        self.runButton.setGeometry(QtCore.QRect(180, 380, 215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(13)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.filelabel = QtWidgets.QLabel(Dialog)
        self.filelabel.setGeometry(QtCore.QRect(180, 340, 215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filelabel.setFont(font)
        self.filelabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.filelabel.setObjectName("filelabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 100, 261, 241))
        self.label_2.setStyleSheet("image: url(:/Icon/ResourceImage/Icon.png);\n"
"border-bottom-right-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face-Nest"))
        self.runButton.setText(_translate("Dialog", "Start"))
        self.filelabel.setText(_translate("Dialog", "Welcome to Face-Nest"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
